services:
  ecommerce-service:
    image: docker.io/library/mysql:8.0
    restart: always
    env_file:
      - .env 
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
